### ISSUE TITLE
Cannot start the container in Ubuntu 20.04 (alerts container fails and the WEB UI gives an error)

### ISSUE THREAD

**Issue by Palezvar** [cuebook/CueObserve#239]
I started the installation on a fresh Ubuntu 20.04 system. When I follow the instructions on the web site, the front-end and alert containers fail. 

My solution was to modify the .env file and point all the links to localhost. This fixed my issue with the front-end container. But the alert container is still broken with the following log:

Traceback (most recent call last):
  File "/code/run.py", line 1, in <module>
    from src.app import app
  File "/code/src/app.py", line 2, in <module>
    from flask import Flask, request, jsonify
  File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)

Another issue is that when I try to access the WEB UI remotely using {IP address}:3000 I get a blank page with a popup error on the top right saying: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Please advise.

**Comment by Palezvar** [comment]
[frontend docker logs.txt](https://github.com/cuebook/CueObserve/files/12835451/frontend.docker.logs.txt)

Please find attached the dcker logs for the front end container

**Comment by Palezvar** [comment]
I think I fixed it, and this is how I did it: (Please note that I did this for version 0.3.2)

- I cloned the project to the local system
- Went into the "CueObserve/alerts-api" folder. Opened the requirements.txt file
- Modified it to look like the following:
   Flask==2.2.3
   gunicorn==20.0.4
   slack-sdk==3.9.1
   Faker==11.3.0
   Werkzeug==2.2.2
- From the same folder I built the docker image for the alerts-api: (Please note that the image name I chose is important here)
  docker build -t cuebook/cue-observe-alerts:0.3.2 .
- Once the image is built, I went back to the project folder "CueObserve" and entered the following:
  docker-compose -f docker-compose-prod.yml --env-file .env up -d

That's it. In business...
